library(ggmap)
library(ggplot2)
library(RColorBrewer)
library(grDevices)
library(scatterplot3d)

am2 <- read.table(file="/Users/josec/Desktop/Planigale/June2017/June9PosterMeeting/Poster/PtmergeddataI.txt",header=TRUE,sep="\t")
dat<-am2
palette(brewer.pal(12,"Set3"))
lbound<-c(min(dat$LON),min(dat$LAT));ubound<-c(max(dat$LON),max(dat$LAT))
bounds<-c(lbound,ubound);Category<-factor(dat$COI_both);options(warn=-1)
print(bounds)
map<-get_map(location=bounds,zoom=6,maptype="satellite");options(warn=1)
plot(ggmap(map)+ggtitle("Map by Admixture Group")+geom_point(data = am2,aes(LON,LAT,colour=factor(Sgroup),size=1),show.legend = FALSE)+scale_color_brewer(palette="Accent"))
pdf("%s%s_PCA_AdmixGroup_%d_%sTC.png", width=1000, height=1000)
myAPCAplot<-ggplot(am2,aes(x=V2,y=V3,color=factor(Sgroup)))+ggtitle("PCA by Admixture K=%s")+geom_point(size=4,show.legend=F)+scale_color_brewer(palette="Accent")+theme_light(base_size=16)+labs(x="PCA axis 1",y="PCA axis 2")
print(myAPCAplot)
aout <- read.table(file="%s",header=TRUE)
am2 <- merge(dat,aout,by.x="Sample",by.y="Sample")





plot
dat <- read.table(file="%s%s",header=TRUE,sep="\t")
evec <- read.table(file="%s%s.evec")
m2 <- merge(dat,evec,by.x="Sample",by.y="V1")
lbound<-c(min(dat$LON),min(dat$LAT));ubound<-c(max(dat$LON),max(dat$LAT));bounds<-c(lbound,ubound);Category<-factor(dat$COI_both);options(warn=-1)
map<-get_map(location=bounds,zoom=7,maptype="satellite");options(warn=0)
plot(ggmap(map)+ggtitle("Map by Pop")+geom_point(data = dat,aes(LON,LAT,colour=Category,size=1),show.legend=T)+scale_color_brewer(palette="Set3"))
png("%s%s_PCA_Pop_%sTC.png", width=1000, height=1000)
myplot<-ggplot(m2,aes(x=V2,y=V3,color=factor(COI_both)))+ggtitle("PCA by Pop")+geom_point(size=4,show.legend=T)+scale_color_brewer(palette="Set3")+theme_light(base_size=16)+labs(x="%s",y="%s")
print(myplot)
palette(brewer.pal(12,"Set3"))
png("%s%s_PCA3D_Pop_%sTC.png", width=1000, height=1000)
myplot3D<-scatterplot3d(m2$V2,m2$V3,m2$V4,pch=16,color=as.numeric(m2$COI_both))
print(myplot3D)
cvs <- read.table(file="cv.txt",header=FALSE)
png("CV_plot_%sTC.png", width=1000, height=1000)
cvplot<-ggplot(cvs,aes(x=V1,y=V2))+geom_point(size=4)+geom_line(col="red")+theme_light()+theme(text = element_text(size=20))+labs(x="k",y="CV error",size=4)
print(cvplot)
evec <- read.table(file="%s%s.evec")
am2 <- merge(am2,evec,all.x=TRUE,by.x="Sample",by.y="V1")
plot(ggmap(map)+ggtitle("Map by Admixture Group")+geom_point(data = am2,aes(LON,LAT,colour=factor(Sgroup),size=1),show.legend = FALSE)+scale_color_brewer(palette="Accent"))
png("%s%s_PCA_AdmixGroup_%d_%sTC.png", width=1000, height=1000)
myAPCAplot<-ggplot(am2,aes(x=V2,y=V3,color=factor(Sgroup)))+ggtitle("PCA by Admixture K=%s")+geom_point(size=4,show.legend=F)+scale_color_brewer(palette="Accent")+theme_light(base_size=16)+labs(x="PCA axis 1",y="PCA axis 2")
print(myAPCAplot)
aout <- read.table(file="%s",header=TRUE)
am2 <- merge(dat,aout,by.x="Sample",by.y="Sample")